# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/hunter/Chip-8_Emulator

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/hunter/Chip-8_Emulator

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hunter/Chip-8_Emulator/CMakeFiles /home/hunter/Chip-8_Emulator/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/hunter/Chip-8_Emulator/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Chip-8

# Build rule for target.
Chip-8: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Chip-8
.PHONY : Chip-8

# fast build rule for target.
Chip-8/fast:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/build
.PHONY : Chip-8/fast

src/SDLMain.o: src/SDLMain.c.o

.PHONY : src/SDLMain.o

# target to build an object file
src/SDLMain.c.o:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/SDLMain.c.o
.PHONY : src/SDLMain.c.o

src/SDLMain.i: src/SDLMain.c.i

.PHONY : src/SDLMain.i

# target to preprocess a source file
src/SDLMain.c.i:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/SDLMain.c.i
.PHONY : src/SDLMain.c.i

src/SDLMain.s: src/SDLMain.c.s

.PHONY : src/SDLMain.s

# target to generate assembly for a file
src/SDLMain.c.s:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/SDLMain.c.s
.PHONY : src/SDLMain.c.s

src/decoder.o: src/decoder.c.o

.PHONY : src/decoder.o

# target to build an object file
src/decoder.c.o:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/decoder.c.o
.PHONY : src/decoder.c.o

src/decoder.i: src/decoder.c.i

.PHONY : src/decoder.i

# target to preprocess a source file
src/decoder.c.i:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/decoder.c.i
.PHONY : src/decoder.c.i

src/decoder.s: src/decoder.c.s

.PHONY : src/decoder.s

# target to generate assembly for a file
src/decoder.c.s:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/decoder.c.s
.PHONY : src/decoder.c.s

src/intructions.o: src/intructions.c.o

.PHONY : src/intructions.o

# target to build an object file
src/intructions.c.o:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/intructions.c.o
.PHONY : src/intructions.c.o

src/intructions.i: src/intructions.c.i

.PHONY : src/intructions.i

# target to preprocess a source file
src/intructions.c.i:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/intructions.c.i
.PHONY : src/intructions.c.i

src/intructions.s: src/intructions.c.s

.PHONY : src/intructions.s

# target to generate assembly for a file
src/intructions.c.s:
	$(MAKE) -f CMakeFiles/Chip-8.dir/build.make CMakeFiles/Chip-8.dir/src/intructions.c.s
.PHONY : src/intructions.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... Chip-8"
	@echo "... src/SDLMain.o"
	@echo "... src/SDLMain.i"
	@echo "... src/SDLMain.s"
	@echo "... src/decoder.o"
	@echo "... src/decoder.i"
	@echo "... src/decoder.s"
	@echo "... src/intructions.o"
	@echo "... src/intructions.i"
	@echo "... src/intructions.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

